name: Node CI

on:
  push:
    branches:
      - main
    paths:
      - errata.html
  pull_request: {}

jobs:
  generate-errata:
    name: Generate errata
    runs-on: ubuntu-latest # only linux supported at present
    steps:
      - uses: actions/checkout@v4
      - uses: w3c/spec-prod@v2
        with:
          SOURCE: errata.html
          TOOLCHAIN: respec
          VALIDATE_LINKS: false
          VALIDATE_PUBRULES: false
          GH_PAGES_BRANCH: gh-pages
